//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoEmpleado
    {
        public int ProyectoId { get; set; }
        public int EmpleadoId { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
